#!/usr/bin/python

import argparse
import json
import os
import subprocess

os.environ['PATH'] = '%s:%s' % (os.path.dirname(os.path.abspath(__file__)), os.environ['PATH'])

parser = argparse.ArgumentParser(
            description='Create all indices listed in sadvisor JSON output')
parser.add_argument('json_name', help='name of the input JSON file')
args = parser.parse_args()

with open(args.json_name, 'r') as json_file:
    output = json.loads(''.join(json_file.readlines()))

for index in output['indexes']:
    if len(index['path']) > 1:
        hash_fields = ','.join([field.replace('.', '_') for field in index['hash_fields']])
        order_fields = ','.join([field.replace('.', '_') for field in index['order_fields']])
        extra = ','.join([field.replace('.', '_') for field in index['extra']])
    else:
        hash_fields = ','.join([field.split('.')[-1] for field in index['hash_fields']])
        order_fields = ','.join([field.split('.')[-1] for field in index['order_fields']])
        extra = ','.join([field.split('.')[-1] for field in index['extra']])

    csv_name = '_'.join(index['path'])
    key = index['key']
    if extra == 'id' or extra == '':
        extra = ''
    else:
        extra = '--extra ' + extra
    if order_fields:
        order = '--order ' + order_fields
    else:
        order = ''

    cmd = 'csvindex %s %s %s %s index/%s' % (extra, order, csv_name, hash_fields, key)
    print(cmd)
    subprocess.call(cmd, shell=True)
