#!/bin/sh
set -e
set -x

export PATH=`pwd`:~/apps/cassandra/bin:$PATH

create_database.php; sleep 10
(cd csv; csvimport RUBiS)

csvindexrel

csvjoinall

for json_file in "$@"; do
    create_database_json.php "$json_file"
done

sleep 10

for json_file in "$@"; do
    csvindexjson "$json_file"
done

(cd csv/index; csvimport -i RUBiS)
