#!/bin/bash
set -x
set -e

mkdir -p csv/index

./csvindex -r users nickname,password index/auth
./csvindex -r users region index/region

./csvindex -r items seller index/seller_id
./csvindex -r items category index/category_id

./csvindex -r olditems seller index/old_seller_id
./csvindex -r olditems category index/old_category_id

./csvindex -r bids item_id index/bid_item
./csvindex -r bids user_id index/bid_user

./csvindex -r comments from_user_id index/from_user
./csvindex -r comments to_user_id index/to_user
./csvindex -r comments item_id index/item

./csvindex -r buynow buyer_id,date index/buyer
./csvindex -r buynow item_id index/buy_now_item
