#!/usr/bin/python

import argparse
import json
import subprocess

parser = argparse.ArgumentParser(
            description='Create all indices listed in sadvisor JSON output')
parser.add_argument('json_name', help='name of the input JSON file')
args = parser.parse_args()

with open(args.json_name, 'r') as json_file:
    output = json.loads(''.join(json_file.readlines()))

for index in output['indexes']:
    fields = ','.join([field.split('.')[-1] for field in index['fields']])
    extra = ','.join([field.split('.')[-1] for field in index['extra']])
    csv_name = index['path'][0]
    key = index['key']
    if extra == 'id':
        extra = ''
    else:
        extra = '--extra ' + extra
    subprocess.call('./csvindex %s %s %s index/%s' % (extra, csv_name, fields, key), shell=True)
